# Generated by Django 2.1.7 on 2019-03-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.AddField(
            model_name='video',
            name='link',
            field=models.CharField(default='', max_length=400),
        ),
    ]
