# Generated by Django 2.1.7 on 2019-03-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, default='h', max_length=400, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
