# Generated by Django 2.1.7 on 2019-03-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_auto_20190316_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
